# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pytest
      env:
        CLARIFAI_USER_EMAIL: ${{ secrets.USER_EMAIL }}
        CLARIFAI_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      shell: bash
      run: |
        export PYTHONPATH=.
        export CLARIFAI_APP_ID="$(python scripts/setup_app_and_key.py --create-app py-gh-yaml2workflow)"
        export CLARIFAI_API_KEY="$(python scripts/setup_app_and_key.py --create-key ${CLARIFAI_APP_ID})"
        pip install pytest
        pytest tests/
        python scripts/setup_app_and_key.py --delete-app ${CLARIFAI_APP_ID}